name: Cypress Integration Tests

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
